baseurl: /
languageCode: en-US
title: Humboldt Portfolio Management
theme: hugo-lithium
baseURL: 'https://example.com/'
enableEmoji: true
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: Home
      url:  / 
      weight: 1
    - name: Strategy
      url: /strategy/
      weight: 2
    - name: Knowledge
      url: /knowledge/
      weight: 3
    - name: People
      url: /people/
      weight: 4
    - name: GitHub
      url: https://github.com/philipptolios/PPP
      weight: 5
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: /img/faviconn.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.jpg
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
